#!/bin/bash
 
# RUN_AS: The user to run fisheye as. Its recommended that you create a separate user account for security reasons
RUN_AS=stash
 
# STASH_INSTALLATION: The path to the Stash installation. Its recommended to create a symbolic link to the latest version so
# the process will still work after upgrades.
STASH_INSTALLATION="/opt/atlassian-stash-3.6.1"
STASH_HOME="/opt/stash-home"
stashctl() {
        if [ "x$USER" != "x$RUN_AS" ]; then
                su - "$RUN_AS" -c "export STASH_HOME=$STASH_HOME;$STASH_INSTALLATION/bin/$1"
        else
                "export STASH_HOME=$STASH_HOME;$STASH_INSTALLATION/bin/$1"
        fi
}
 
case "$1" in
        start)
                stashctl start-stash.sh
                ;;
        stop)
                stashctl stop-stash.sh
                ;;
        restart)
                stashctl stop-stash.sh
                sleep 10
                stashctl start-stash.sh
                ;;
        *)
                echo "Usage: $0 {start|stop|restart}"
esac
 
exit 0