# -*- mode: ruby -*-
# vi: set ft=ruby :
VAGRANTFILE_API_VERSION = "2"
$bootstrap = <<SCRIPT
sudo sed -i -f - /etc/apt/sources.list <<EOF
1i\deb mirror://mirrors.ubuntu.com/mirrors.txt precise main restricted universe multiverse \\\\
deb mirror://mirrors.ubuntu.com/mirrors.txt precise-updates main restricted universe multiverse \\\\
deb mirror://mirrors.ubuntu.com/mirrors.txt precise-backports main restricted universe multiverse \\\\
deb mirror://mirrors.ubuntu.com/mirrors.txt precise-security main restricted universe multiverse \\\\
EOF
sudo apt-get -y update 
sudo apt-get -y install default-jdk
sudo apt-get -y install git
#cd /vagrant/Hello
#git init
#cd /vagrant/Hello/result
#java HelloRacheli

#sudo adduser git

sudo su git
cd
mkdir .ssh && chmod 700 .ssh
touch .ssh/authorized_keys && chmod 600 .ssh/authorized_keys
#cat /vagrant/github_rsa.pub AAAAB3NzaC1yc2EAAAADAQABAAABAQChPuOQcxRptdFdEOhd65skRceYW6xzPYWnWlClC8VBncv+b06gyGZtRLT6mTLqnLE0rpBFJeLJ7vrl9JpODUrYBJN1vpzCUnyjyvVfxZC8rKsFzJieUj3qStpFuCd44OBwpVxNME7CfxVYG9h6r22lZ+WyR/9lOBr5bk4QGe84fp986IHXVPlF16Pz9ujSu3m9EpBNX/VD8cy/AVyMq+5mPTh03NtIOphK7GvBclKXRNaPqF7rWzPM3XhJPA7/qCWZI61QsDZEXsI7LGI6aNzQcMjR5BLPknDStSzFT/qvlvU3tJv4o5FXbNC9vmx/Kx6elBguDUB03juxuX4DVJW5 
cat /vagrant/github_rsa.pub >> ~/.ssh/authorized_keys
cd /
mkdir project.git
cd project.git
git init --bare

SCRIPT

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|
	config.vm.box = "hashicorp/precise64"
	config.vm.provider "virtualbox" do |v|
		v.memory = 1024
		v.cpus = 2
	end 
	config.vm.provision "shell", inline: $bootstrap
  
end
